# Use a imagem mais leve do OpenJDK 21
FROM openjdk:21-slim

# Instala o Git no container
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Instale o cliente MySQL
RUN apt-get update && apt-get install -y default-mysql-client

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o protótipo jar no diretório de trabalho
COPY nexusJava_ETL/PrototipoJar.jar .

# Copie o script de espera para o container
COPY wait-for-mysql.sh .

# Torne o script de espera executável
RUN chmod +x /app/wait-for-mysql.sh

# Comando para rodar o aplicativo, aguardando o MySQL estar pronto
CMD ["sh", "-c", "/app/wait-for-mysql.sh db && java -jar PrototipoJar.jar && tail -f /dev/null"]
