# Use a imagem oficial do Node.js como imagem base
FROM node:latest

# Instale o Git no container para poder clonar o repositório
RUN apt-get update && apt-get install -y git

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copia o package json do nexusEnergy
COPY package*.json ./

RUN npm cache clean --force && npm install --verbose

# Copie o código do projeto para o diretório de trabalho
COPY . .

# Torne o script de espera executável
RUN chmod +x /app/wait-for-mysql.sh

# Exponha a porta que o aplicativo irá rodar
EXPOSE 3333

# Comando para rodar o aplicativo
CMD ["sh", "/app/wait-for-mysql.sh", "db", "node", "app.js"]