# Use a imagem mais leve do OpenJDK 21
FROM openjdk:21-slim

# Instala o Git no container
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho dentro do container
WORKDIR /app

COPY nexusJava_ETL/PrototipoJar.jar .

# Executa o arquivo JAR
CMD ["java", "-jar", "PrototipoJar.jar"]

