FROM mysql:latest

# copie os scripts SQL de inicialização para um diretório temporário no container

COPY ./arquivos_sql/ /docker-entrypoint-initdb.d/

# exponha a porta padrão do MySQL

EXPOSE 3306
